Integration Tests (1st batch)
radicle-dev/drips-js-sdk pull request #110
Opened 2023-01-11 16:01 UTC by jtourkos

- Refactored `NFTDriverClient` & `DripsHubClient` creation API. 
- Added `NFTDriverClient` integration tests.

2023-01-11 16:31 UTC, efstajas requested changes

2023-01-11 16:31 UTC, efstajas commented on src/NFTDriver/NFTDriverClient.ts
> +	 * @param  {JsonRpcProvider} provider The network provider. It cannot be changed after creation.
This should probably be `{Provider}`, right? (Could also just remove the jsdoc typings and they'd be inferred from the TS function signature)

2023-01-11 16:31 UTC, efstajas commented on src/NFTDriver/NFTDriverClient.ts
> +	 * @param  {JsonRpcProvider} signer The singer used to sign transactions. It cannot be changed after creation.
should be typed as signer?

2023-01-11 16:31 UTC, efstajas commented on src/DripsHub/DripsHubClient.ts
>  		customDriverAddress: string | undefined = undefined
```suggestion
		signer?: Signer,
		customDriverAddress?: string,
```

2023-01-13 12:33 UTC, jtourkos commented on src/NFTDriver/NFTDriverClient.ts
> +	 * @param  {JsonRpcProvider} signer The singer used to sign transactions. It cannot be changed after creation.
Yes, changed.

2023-01-13 12:35 UTC, jtourkos commented on src/NFTDriver/NFTDriverClient.ts
>  		customDriverAddress: string | undefined = undefined
✅

2023-01-13 12:40 UTC, merged

2023-01-13 12:40 UTC, jtourkos commented
I applied the changes and also changed the waiting time to use [this](https://github.com/radicle-dev/drips-app-v2/blob/main/src/lib/utils/expect.ts). Nice tip @efstajas!