Encapsulate validation logic, decouple from specific provider class, change from network name to chain ID in initialisation
radicle-dev/drips-js-sdk pull request #36
Opened 2022-06-17 14:52 UTC by jtourkos

Hey team!👋 
This one contains quite a few **breaking** changes but hopefully, it'll simplify the usage of the `DripsClient`.  

Let me summarise the most important points. 🤓

1. The creation of a `DripsClient` instance is no longer performed via the normal constructor, but instead via the `static async create(config: DripsClientConfig): Promise<DripsClient>` factory method.

This method **encapsulates all validation logic** making sure the users get back a fully functional client instance without possible surprises of chain IDs not matching, undefined signer, etc., and the need to call a `connect()` method at a later point. 

Internally, it performs the validation logic and then delegates the creation to a *private* constructor. Now, if a “curious” user still wants to mess with the initialization logic, properties, etc, for some reason, they still can, via JavaScript’s “deeper features”…  For more on this, you can take a look [here](https://github.com/radicle-dev/drips-js-sdk/issues/9), at Matt’s detailed comments, and why this is *not* true encapsulation. But, in my opinion, the goal of a library is to drive its “normal” users to proper usage, and this is what we are trying to do with this kind of encapsulation. There is no security risk compared to the previous version, in which we already exposed *everything*. You can consider it somehow as being one more “encapsulation layer up”.

2. The `DripsClientConfig` is:
    
    ```tsx
    type DripsClientConfig = {
    	signer: Signer;
    	chainId: SupportedChain;
    	provider: Provider | Web3;
    }
    ```
    
    This is another big difference. Previously, `DripsClient` ’s `constructor(provider: providers.Web3Provider, networkName: string)` was accepting two things. A Web3Provider and a network name (`string`). 
    
    Firstly, if you noticed the `DripsClientConfig` type,  it expects *both* a provider and a signer. The provider is a _base_ Provider and *not* a *specific* provider type like Web3Provider, decoupling the client from this concrete class, and allowing users to pass not only UI/metamask/walletconnect providers, but also testing providers, “backend” providers, etc.
    
    One step further, to be more flexible, we allow a provider to be `Provider | Web3` so that we support both ethers.js and web3.js providers. The issue is, that these two libraries have a different approaches when it comes to provider-signer. In ethers, these two concepts are completely decoupled, whereas, in web3, you can get the signer from a provider like this, `provider.getSigner()`. Internally, we transform into ethers.providers.Provider a Web3 provider, hence the need to pass separately a signer object. In my opinion, it is better if *all* dependencies are explicitly passed and not doing things like `provider.getSigner()`.
    
    `DripsClientConfig` also accepts a _chain ID_, where previously we were passing the _network name_ causing some issues as logged in the relevant GitHub issues. For convenience, we also added a type for the supported chain IDs (`type SupportedChain = 1 | 4 | 137 | 80001`), but in any case, everything is validated and an exception is thrown in case something is not as expected.
    
3. Because all validation logic is performed in the `create()` method, the rest of the methods are simplified by removing “invalid arguments” checks/exceptions.
4. Minor improvements:
    1. Added types for the contract details, network names, etc.
    2. Some renamings.
    3. Cleanup of the errors, codes, and messages.
    4. Added and updated unit tests
    

Related issues:

- https://github.com/radicle-dev/drips-js-sdk/issues/34
- https://github.com/radicle-dev/drips-js-sdk/issues/10
- https://github.com/radicle-dev/drips-js-sdk/issues/9

Please feel free to share your thoughts! 😊 This is one approach, and I'd be happy to hear what you think about it, if you see any potential issues, or other ways we can proceed! 🙌

It'll be also very interesting to see how easy it would be (and if it works as expected) to integrate this new logic into the drips app and workstreams.

2022-06-18 15:12 UTC, gh0stwheel commented
Overall this looks good to me!

I guess the one question or consideration that I would like to raise is that with these changes, we do sort of move from DripsClient being a mutable/stateful type to more of an immutable/stateless one in the sense that in the existing design we had sort of started down the path of trying to allow parameters like network, signer etc. to change and then also allowed the DripsClient to be either connected or disconnected.

Obviously all of that was not at all robustly implemented in the existing version, so this may be more of a distinction in theory than in practice, but it did set a kind of pattern for future development which we are now changing with this PR to go in quite a different direction.

I am not at all familiar with the nuts and bolts details of how these Providers work, but I think that the place where this will matter is around the question of how we expect that developers building on DripsClient will be able to listen for and react to changes in the underlying provider state. In the existing paradigm, my high-level sense was that we were going to try handle some of these changes for them inside of DripsClient, where that made sense. Namely, that we would listen for changes coming from the Provider (e.g. if the end-user makes changes to the selected network, or signer in Metamask), and then we would update all of these values accordingly in DripsClient and possibly provide our own set of listeners so that code building on top of DripsClient could be notified. Everett has some code along these lines in the current Drips App implementation which I did not bring over when I initially implemented DripsClient.

In the new paradigm, my sense is that developers themselves will be expected to listen on the Provider type directly, and react to any changes by simply building a whole new DripsClient and switching over to using that. I actually don't have any strong opinion on whether this is the right or wrong way to go, but I do want to note that it is a significant change in terms of the high-level approach for DripsClient, so it's good to make sure we feel confident about it.

This seems like a design decision where it might be interesting to see how Superfluid and other JS SDKs that have built on Provider have decided to proceed (ie. with a stateful, or stateless client class). @jtourkos @efstajas @mattosborn @cloudhead -- are you aware of any other more well-developed web3 JS projects that we could use as a reference for the right direction to take here?

2022-06-18 21:17 UTC, jtourkos commented
Great points @gh0stwheel! Sharing some thoughts on the concerns you raised.

> I guess the one question or consideration that I would like to raise is that with these changes, we do sort of move from DripsClient being a mutable/stateful type to more of an immutable/stateless one in the sense that in the existing design we had sort of started down the path of trying to allow parameters like network, signer, etc. to change and then also allowed the DripsClient to be either connected or disconnected.

>Obviously all of that was not at all robustly implemented in the existing version, so this may be more of a distinction in theory than in practice, but it did set a kind of pattern for future development which we are now changing with this PR to go in quite a different direction.

I completely see your concern here. But let's see these changes from a different angle that might not look like we're heading in a (totally) different direction.

Coming from a strict DDD background I am always very careful with _public_ setters. 
Of course, there is nothing wrong with allowing a library's client to set _some_ of its properties.
The question is _how_ though.
How does the library's API allow its users to do to it?

One way is to make a property `public`. Then a user can simply do something like `myProperty = newValue;`
Depending on the context, this might be "dangerous". 
Does the user know the possible _side effects_ an assignment to a _state_ variable can have?

Now, what is our case?
_All_ properties (`provider`, `signer`, `address`, `networkId`, `contractDetails`, `daiContract`, `hubContract`) are public. 

Especially, the `provider` is one we need to pay attention to. 
Let's consider the following scenario:

The user initially sets the `provider` when instantiating a new `DripsClient` instance: 
`const client = new DripsClient(myProvider, 'rinkeby');`.

Then, the user needs (not to forget) to connect:
`await client.connect();`

Look what happens now. Internally, the `connect()` method sets the signer based on _this_ provider: `this.signer = this.provider.getSigner();`

So, if, at a later point the user does something like:
`dripsClient.provider = myNewProvider;`

Do they know that they need to call `connect()` _again_ to set the new singer? Because changing the provider (which it's public) would _not_ affect the singer unless the user re-connects. Or do they suppose, **since they are allowed to do so**, that the library automatically manages this for them? 

From an API design perspective, this might not be very obvious.

Note also, that not calling the `connect()` at all (resulting in an undefined singer) will throw exceptions.
 
The singer is a very important dependency, shouldn't be _explicitly_ passed?

Another reason for explicitly passing the `singer` property is that ethers.js treats singers differently from web3.js.
In ethers.js the singer is not always related to the provider object (technically speaking). In the current implementation, that expects a `Web3Provider` the signer is _always_ retrieved from the provider (but remember, it's also a public property).

The same concern is about the networkId property. There is a public setter but it's also being _extracted_ from the `provider` property:`this.networkId = (await this.provider.getNetwork()).chainId;` (which can be changed any time and the user will not know this side effect...). 

You see the point.

It is a matter of guiding the users to proper usage of the library - in an intuitive way, and not allowing them to do something wrong (to the point we can).

Now since we are here. Regarding the `connect()` and `disconnect()` methods.
Those methods are "wrappers" on top of some properties, and considering that the `connect()` method _must_ be called for the client to be fully functional, this is logic and validation that the _library_ needs to _encapsulate_ and not delegate the call order to the users. 

I'd say that the `connect()` _functionality_ is not removed in the suggested changes, but instead, consolidated into the `create()` method together with the necessary validations, removing also the need for two method calls (`constructor` and `connect()`).

About the `disconnect()`. Currently, `disconnect()` just "nulls out" some properties (still leaving the provider to exist).
This is a "higher-level" question. Does a `DripsClient` make sense to exist without some basic properties? How are we expecting our users to interact with the client?

Two scenarios:

_One_ client that they can connect and disconnect from. In this case, `connect()` should accept _all_ the necessary dependencies (provider, signer, and chainID/network name) - explicitly.
`disconnect()` should null those properties out.

The other option is the suggested changes. The user expects to create a fully functional object - **"coupled" to some parameters** (provider, signer, and chainID/network name) - and dispose it after it's no longer needed. 
If there is a need to change for example a provider, then the user will create a new instance of the `DripsClient`.

Based on this logic, the `signIn()` and `signOut()` API was no longer needed, as it was also a wrapper on top of setter calls.

I hope it's clear thus far, that the suggested changes do not propose a change in the _what_ it's being exposed and allowed to be set, but on the _how_ we do it. 
So I'd say that it is not so much a question of mutability/immutability but rather a matter of encapsulation, maybe.
We can still allow _any_ property we decide to be modifiable, but the question is how, where, how many times, etc.

Also, as a general rule of thumb, I'd always start with the _minimal_ public API, and then, according to the users' needs, we can "open" more.
For two main reasons. Mainly because less public surface means less room for errors, and secondly because gradually opening up, you can think of the logic and validation better.

Small note. These are some design thoughts, leaving aside the technical implementation details of JavaScript about what is truly private, etc.

> I am not at all familiar with the nuts and bolts details of how these Providers work, but I think that the place where this will matter is around the question of how we expect that developers building on DripsClient will be able to listen for and react to changes in the underlying provider state. In the existing paradigm, my high-level sense was that we were going to try to handle some of these changes for them inside of DripsClient, where that made sense. Namely, we would listen for changes coming from the Provider (e.g. if the end-user makes changes to the selected network or signer in Metamask), and then we would update all of these values accordingly in DripsClient and possibly provide our own set of listeners so that code building on top of DripsClient could be notified. Everett has some code along these lines in the current Drips App implementation which I did not bring over when I initially implemented DripsClient.

> In the new paradigm, I sense that developers themselves will be expected to listen to the Provider type directly, and react to any changes by simply building a whole new DripsClient and switching over to using that. I don't have any strong opinion on whether this is the right or wrong way to go, but I do want to note that it is a significant change in terms of the high-level approach for DripsClient, so it's good to make sure we feel confident about it.

On your point about the `provider`:
The only thing that changed is the _type_ of the provider object. 
Instead of having a dependency on a concrete provider class (`Web3Provider`), we now depend on the _base_ class allowing more provider types to work with the library. Note that `Web3Provider` is only a "UI" provider. This means that **a user cannot use the client in the backend (or for integration testing)**. 
But this is a very good point and something that I need to validate - probably with  @evvvritt (that we don't break the " [...]

2022-06-20 16:33 UTC, cloudhead commented on package.json
> +		"web3": "^1.7.3",
Why depend on web3? This is a large dependency that is redundant given ethers.

2022-06-20 16:38 UTC, cloudhead commented
I'm generally supportive of these changes from a high level, the only issue I have is pulling in web3.js, which no one on the team is using.

2022-06-20 18:31 UTC, gh0stwheel commented
Thanks for sharing all of these thoughts and details @jtourkos. Given the many points you make, I agree that this all makes a lot of sense.

Since this is a major change, let's give @evvvritt and @mattosborn one more day to see if they have any thoughts to share and otherwise we can plan to merge these changes tomorrow!

2022-06-20 18:33 UTC, gh0stwheel commented
(modulo @cloudhead's question about web3.js as well....)

2022-06-20 22:42 UTC, mattosborn requested changes
PR looks great! There are only a handful of smaller issues I've left comments on.

And here's some feedback on some of the other issues raised in previous comments...

### Web3 dependency

On @cloudhead's comment on `web3` being pulled in. This is only a dev dependency and so no code should be imported into the runtime / build. This is why I've suggested being careful to make sure this kind of dependency (1) is only ever imported using a type-only import and (2) is in `devDependencies` in package.json. This is both for sanity and readability.

### Immutability

My general stance/philosophy on this is that immutability should be the default everywhere unless there are good reasons why not, and I think it's actually fairly rare that there's a good case for mutability. I'd guess immutability is a good thing here. To echo @jtourkos's comments I think two important factors for libraries are (1) making them intuitive to use and (2) making them very difficult or impossible to mis-use/break. I think immutability contributes positively to these goals and I'm not sure there's a good argument against it.

### Provider changes

I don't have experience working with providers or `ethers`, and so I'd defer to recommended best practices on this ([link](https://docs.ethers.io/v5/concepts/best-practices/#best-practices--network-changes))

2022-06-20 22:42 UTC, mattosborn commented on src/utils.ts
> +import Web3 from 'web3';
I think it's generally worth being explicit with type-only imports rather than relying on tooling to work it out.

2022-06-20 22:42 UTC, mattosborn commented on src/utils.ts
> +				`Cannot retrieve collectable amount: invalid Etherium address - '${receiver}'.`,
sp

2022-06-20 22:42 UTC, mattosborn commented on src/utils.ts
> +				`Cannot retrieve collectable amount: invalid Etherium address '${receiver}'.`,
sp

2022-06-20 22:42 UTC, mattosborn commented on src/utils.ts
> +			`Cannot retrieve collectable amount: invalid Etherium address - "${input}" is not an Ethereum address`,
sp

2022-06-21 08:29 UTC, jtourkos commented on src/dripsclient.ts
> +/* eslint-disable max-classes-per-file */
Yes, you're right. Removed the unnecessary comment.

2022-06-21 08:42 UTC, jtourkos commented on src/dripsclient.ts
> +			throw DripsErrors.invalidConfiguration('Cannot create instance: provider is missing.');
Good catch. But in my opinion, it should probably be the other way around.
We should also remove it from the other places as well (where it makes sense).

The idea of the context was to provide some additional information in case the message was not descriptive enough (that's why it's also an optional parameter).

In these cases, I believe just the error messages will work fine (?). No need for extra lines of code.

2022-06-21 09:15 UTC, jtourkos commented on src/dripsclient.ts
> +		if (providerNetwork.chainId !== config.chainId) {
Hmm, very good point. I guess this came from the current implementation in which we pass the provider and the _network name_, and [this](https://github.com/radicle-dev/drips-js-sdk/issues/34) issue where we wanted to switch to the _chain ID_.

But your question is actually valid. Is there a reason why we'd want to pass both? 
@efstajas and @evvvritt what do you say? You logged this feature so you may have a better understanding of some use cases why we'd need both.

As a quick thought, accepting also the chain ID (or the network name) provides some kind of type-safety to the users regarding the _supported_ networks. Passing only the provider, a user could pass whichever network they prefer, supported or not, and in the case of an unsupported network, they'll get back an error - after initialization.

(but knowing how strongly type TypeScript/JavaScript is, this could, either way, be bypassed and a user can pass an unsupported network in the first place).

2022-06-21 09:17 UTC, jtourkos commented on src/dripsclient.ts
> +				`Cannot retrieve collectable amount: invalid Etherium address '${address}'`,
Copied and pasted the messages. 😊
All fixed now.

2022-06-21 09:18 UTC, jtourkos commented on src/subgraph.ts
> +			throw DripsErrors.connectionFailed('Cannot not query subgraph: API URL is not specified.');
Fixed fix 😜

2022-06-21 13:36 UTC, evvvritt commented on src/dripsclient.ts
> +		if (providerNetwork.chainId !== config.chainId) {
I think it's nice to pull from the provider.

One consideration is like @jtourkos suggests, ensuring the provider is on a supported network (or the desired one for the app context, like the Polygon version of the drips app). But we could just defer this check onto the developer to handle as they please (ie the developer should ensure the provider they pass is on a desired network first.)

Thoughts?

2022-06-21 13:57 UTC, jtourkos commented on src/utils.ts
> +import Web3 from 'web3';
(will reply below)

2022-06-21 13:59 UTC, jtourkos commented on package.json
> +		"typedoc": "^0.22.17"
(will reply below)

2022-06-21 14:10 UTC, jtourkos commented
@cloudhead @mattosborn 

Based on Matt's feedback, and reading a bit more to understand better the role of "peerDependecies" (and the relevant `type only imports`), I've reverted the `package.json` file to only contain "devDependencies" and "peerDependencies".

Just to confirm my understanding before committing the changes:

1. `ethers.js` should be a _peer_ dependecy and state the version our library supports. It'll be up to the library _user_ to include it in their project. Our package will not (?) include `ethers.js`.
2. We include _anything_ (in "devDependencies") we want its type from , and import the relevant types with `import type`. This should also have no impact (?) on our package, as types are only being used as "shapes" and while developing (?).
3. The reason why `web3.js` will be a "devDependency" and not a "peerDependency" compared with `ethers.js`, is that from `web3.js` we only need the provider _type_ whereas in the case of `ethers.js`, internally, we _use_ the library as well.

Are these points right @mattosborn ? Could you please confirm?

2022-06-21 14:24 UTC, jtourkos commented on src/dripsclient.ts
> +		if (providerNetwork.chainId !== config.chainId) {
@evvvritt 

I agree, yes.

When instantiating a new client like this

`const dripsClient = await DripsClient.create({provider: providerStub, signer: signer});`

developers could pass _any_ provider they like. Internally, `create()`, will validate if the library supports the `provider` argument, and throw a relevant exception if not.

Of course, we should document the supported networks.

2022-06-21 15:16 UTC, mattosborn commented
One thing I'm not sure about on the typedefs + devDependencies side of things is what the best practices are for our type-only dependencies where those types are also exposed in our public interfaces. 

Some thoughts / possible options to look into:

1. **Bundle them with our own typedefs** - Does this lead to duplicated and incompatible typings for lib users?
2. **Don't bundle them** - Does this lead to unresolved types when the dependency is a `devDependency`? This would then require typescript lib users to manually install these typedefs to resolve them which sucks.
3. **Make them regular dependencies** - Is there a way we can indicate they are only used for typings? Is this necessary?

It would be worth testing to see how this works in `drips-sdk` current state and whether or not there are any issues that we need to address. And it would be worth trying to find some js libs built in typescript to see how they handle this too.

2022-06-21 15:21 UTC, jtourkos commented on package.json
> +		"web3": "^1.7.3",
(replying [here](https://github.com/radicle-dev/drips-js-sdk/pull/36#issuecomment-1161800176))

2022-06-23 09:52 UTC, merged